# AMBF registration configuration file
# Author: Hisashi Ishida
# Date: 09.06.2024


## Pointer based registration
pointer:
  tooltip name: /ambf/env/psm1/BODY yaw link # Rigid body that is attached to the tip of the tool
  name of points:
    - Poll_L_0
    - Poll_L_3
    - Poll_R_2
    - Poll_R_5

  object name: Puzzle_origin
